#!/usr/bin/env python3
"""
MARS LaTeX Generator — Internal Module

Generates mars_values.tex with LaTeX macros from JSON files.
Called by mars_run.py after mars_numerics.py completes.

Usage (as module):
    import mars_latex
    mars_latex.generate()

Usage (standalone, for testing):
    python mars_latex.py
"""

import json
from pathlib import Path
from datetime import datetime


def generate(
    params_file: str = "mars_params.json",
    results_file: str = "mars_results.json",
    output_file: str = "mars_values.tex"
) -> None:
    """
    Generate LaTeX macros from JSON files.

    Reads:
        - mars_params.json: Input parameters (fixed + design)
        - mars_results.json: Computed results

    Writes:
        - mars_values.tex: LaTeX \\newcommand definitions
    """
    # Read input files
    with open(params_file) as f:
        params = json.load(f)

    with open(results_file) as f:
        results = json.load(f)

    # Build LaTeX content
    lines = [
        "% MARS parameters - auto-generated, do not edit",
        f"% Generated by mars_latex.py on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
    ]

    # Fixed parameters
    lines.append("% Fixed parameters")
    fixed = params.get("fixed", {})
    add_cmd(lines, "Pbar", fixed.get("P_bar", 15.0), "bar")
    add_cmd(lines, "TK", fixed.get("T_K", 300.0), "K")
    add_cmd(lines, "gammaXe", fixed.get("gamma_Xe", 1.667), "")
    add_cmd(lines, "Rcyl", fixed.get("R_cyl_m", 1.6), "m")
    add_cmd(lines, "Hcyl", fixed.get("H_cyl_m", 1.5), "m")
    add_cmd(lines, "Ldrift", fixed.get("L_drift_m", 1.5), "m")
    add_cmd(lines, "vdrift", fixed.get("v_drift_mm_s", 100.0), "mm/s")
    add_cmd(lines, "sigmadiff", fixed.get("sigma_diff_mm", 1.0), "mm")
    add_cmd(lines, "uc", fixed.get("u_c_mm_s", 0.1), "mm/s")
    lines.append("")

    # Design parameters
    lines.append("% Design parameters")
    design = params.get("design", {})
    add_cmd(lines, "narms", design.get("n_arms", 2), "")
    add_cmd(lines, "Rblade", design.get("R_blade_m", 1.6), "m")
    add_cmd(lines, "chord", design.get("chord_m", 0.16), "m")
    add_cmd(lines, "chordmm", design.get("chord_m", 0.16) * 1000, "mm")
    add_cmd(lines, "mblade", design.get("m_blade_kg", 0.25), "kg")
    add_cmd(lines, "mplate", design.get("m_plate_kg", 0.25), "kg")
    add_cmd(lines, "taumotor", design.get("tau_motor_Nm", 60.0), "N.m")
    add_cmd(lines, "deltar", design.get("delta_r_m", 0.8), "m")
    add_cmd(lines, "rzerocarrier", design.get("r0_carrier_m", 0.8), "m")
    add_cmd(lines, "zlift", design.get("z_lift_mm", 5.0), "mm")
    add_cmd(lines, "tlift", design.get("t_lift_s", 0.5), "s")
    add_cmd(lines, "Factuator", design.get("F_actuator_N", 20.0), "N")
    lines.append("")

    # Gas properties (from results)
    lines.append("% Gas properties")
    gas = results.get("gas_properties", {})
    add_cmd(lines, "rhoxe", gas.get("rho_kg_m3", 79.0), "kg/m3", fmt=".1f")
    add_cmd_sci(lines, "nuxe", gas.get("nu_m2_s", 2.94e-7), "m2/s")
    add_cmd(lines, "csound", gas.get("c_s_m_s", 178.0), "m/s", fmt=".0f")
    lines.append("")

    # Phase 1 results
    lines.append("% Phase 1: Blade rotation")
    p1 = results.get("phase1", {})
    add_cmd(lines, "sweepangle", p1.get("sweep_angle_deg", 180), "deg", fmt=".0f")
    add_cmd(lines, "trot", p1.get("t_rot_ms", 395), "ms", fmt=".0f")
    add_cmd(lines, "trots", p1.get("t_rot_s", 0.395), "s", fmt=".3f")
    add_cmd(lines, "omegamax", p1.get("omega_max_rad_s", 15.9), "rad/s", fmt=".1f")
    add_cmd(lines, "Vtip", p1.get("V_tip_m_s", 25.4), "m/s", fmt=".1f")
    add_cmd(lines, "Matip", p1.get("Ma_tip", 0.14), "", fmt=".2f")
    add_cmd_sci(lines, "Retip", p1.get("Re_tip", 1.4e7), "")
    add_cmd(lines, "deltablade", p1.get("delta_mm", 2.21), "mm", fmt=".2f")
    add_cmd(lines, "deltastar", p1.get("delta_star_m", 0.00028) * 1000, "mm", fmt=".3f")
    add_cmd(lines, "uprimeblade", p1.get("u_prime_m_s", 1.27), "m/s", fmt=".2f")
    add_cmd(lines, "maxreachblade", p1.get("max_reach_mm", 3.25), "mm", fmt=".2f")
    add_cmd(lines, "tdecayblade", p1.get("t_decay_ms", 3.5), "ms", fmt=".1f")
    lines.append("")

    # Phase 2 results
    lines.append("% Phase 2: Carrier slide")
    p2 = results.get("phase2", {})
    add_cmd(lines, "tslide", p2.get("t_slide_ms", 200), "ms", fmt=".0f")
    add_cmd(lines, "tslides", p2.get("t_slide_s", 0.2), "s", fmt=".3f")
    add_cmd(lines, "Vslide", p2.get("V_slide_m_s", 8.0), "m/s", fmt=".1f")
    add_cmd(lines, "deltacarrier", p2.get("delta_mm", 2.78), "mm", fmt=".2f")
    add_cmd(lines, "maxreachcarrier", p2.get("max_reach_mm", 4.00), "mm", fmt=".2f")
    add_cmd(lines, "tdecaycarrier", p2.get("t_decay_ms", 14), "ms", fmt=".1f")
    lines.append("")

    # Phase 3 results
    lines.append("% Phase 3: Vertical lift")
    p3 = results.get("phase3", {})
    add_cmd(lines, "Vlift", p3.get("V_lift_mm_s", 10.0), "mm/s", fmt=".0f")
    add_cmd(lines, "Relift", p3.get("Re_lift", 330), "", fmt=".0f")
    add_cmd(lines, "deltaStokes", p3.get("delta_Stokes_mm", 0.39), "mm", fmt=".2f")
    lines.append("")

    # Summary
    lines.append("% Summary")
    summary = results.get("summary", {})
    add_cmd(lines, "ttotal", summary.get("t_total_s", 1.10), "s", fmt=".2f")
    add_cmd(lines, "ttotalms", summary.get("t_total_ms", 1100), "ms", fmt=".0f")
    add_cmd(lines, "maxreach", summary.get("max_reach_mm", 4.00), "mm", fmt=".2f")
    add_cmd(lines, "margin", summary.get("margin_mm", 1.00), "mm", fmt=".2f")
    add_cmd(lines, "deadzone", summary.get("dead_zone_mm", 110), "mm", fmt=".0f")
    add_cmd(lines, "deadzonepct", summary.get("dead_zone_pct", 7.3), "\\%", fmt=".1f")
    lines.append("")

    # 6 Mechanisms (selected params for documentation)
    lines.append("% 6 Mechanisms")
    mech = results.get("mechanisms", {})
    m2 = mech.get("m2_bulk_swirl", {})
    add_cmd(lines, "tauDrag", m2.get("tau_drag_Nm", 48), "N.m", fmt=".0f")
    add_cmd(lines, "deltaEkman", m2.get("delta_Ekman_mm", 0.14), "mm", fmt=".2f")
    m3 = mech.get("m3_potential_flow", {})
    add_cmd(lines, "tacoustic", m3.get("t_acoustic_ms", 9), "ms", fmt=".0f")
    m4 = mech.get("m4_pressure_pulse", {})
    add_cmd(lines, "dpPulse", m4.get("dp_kPa", 25), "kPa", fmt=".0f")
    m5 = mech.get("m5_secondary_flows", {})
    add_cmd(lines, "acent", m5.get("a_cent_m_s2", 200), "m/s2", fmt=".0f")
    m6 = mech.get("m6_vortex_shedding", {})
    add_cmd(lines, "fshed", m6.get("f_shed_Hz", 270), "Hz", fmt=".0f")
    lines.append("")

    # Write output file
    content = "\n".join(lines)
    with open(output_file, "w") as f:
        f.write(content)

    print(f"LaTeX macros written to: {output_file}")


def add_cmd(lines: list, name: str, value, unit: str = "", fmt: str = "") -> None:
    """Add a \\newcommand line."""
    if fmt:
        val_str = f"{value:{fmt}}"
    else:
        val_str = str(value)
    # Remove trailing zeros for cleaner output
    if "." in val_str:
        val_str = val_str.rstrip("0").rstrip(".")
    lines.append(f"\\newcommand{{\\{name}}}{{{val_str}}}  % {unit}")


def add_cmd_sci(lines: list, name: str, value: float, unit: str = "") -> None:
    """Add a \\newcommand line with scientific notation."""
    # Format as e.g. "2.94e-7" or "1.4e7"
    val_str = f"{value:.2e}"
    lines.append(f"\\newcommand{{\\{name}}}{{{val_str}}}  % {unit}")


def main() -> None:
    """Standalone test."""
    generate()


if __name__ == "__main__":
    main()
